### PR TITLE
Make marks to contain subpages and add geoshape docs

### PR DESCRIPTION
**Pull request by mattijn**
This PR extent the marks in the user guide to contain subpages.
One subpage with documentation related to the `mark_geoshape` is included.

ps. I forgot to add geopandas as dependency in the requirements.txt for the docs.

### CODE REVIEW

**Comment by joelostblom** [comment]
I went through this briefly and it looks great to me! I can do a more full review after https://github.com/altair-viz/altair/pull/2566 is merged. I agree with your comment there and think it would be easier to review small PRs instead of extending the same one, but let's hear what Jake prefers.

**Comment by joelostblom** [comment]
I have wanted to experiment with deploy previews of documentation related PRs for a while so I setup one here on my fork to test. It seems to work well for this PR. Maybe we can add it to the real altair repo at a later stage so that it is easier to review how the documentation changes with a PR without the need to build locally. The changes you made show up nicely on the link above (https://deploy-preview-1--spontaneous-sorbet-49ed10.netlify.app/).

**Comment by mattijn** [comment]
Thats a nice approach of deploying previews. Locally it is a bit of a struggle with making changes and viewing them.

**Comment by mattijn** [comment]
Add a section on classifications:

image

And an example how to use an expression for rotation:

image

The [page](https://deploy-preview-1--spontaneous-sorbet-49ed10.netlify.app/) is becoming a bit slower for loading all the embedded charts..

**Comment by joelostblom** [comment]
Wow I love it! That section on classifications is really neat. Altair is going from the lacking geo-docs to having the best ones out there =D

**Comment by joelostblom** [comment]
@mattijn Now that the original docs revamp that I was working on is merged, could you open up this PR towards the main altair repo instead of my fork? I think the material here is amazing and I want to make sure we don't lose it. I know there is connection to https://github.com/altair-viz/altair/pull/2607 which I have been meaning to get to for some time, and for me it doesn't matter which one we review/merge first, whatever is easier for you.

**Pull request closed without merging**
